spring:
  datasource:
    url: jdbc:mysql://morning-holic-dev.cdcv8za2otre.ap-northeast-2.rds.amazonaws.com:3306/morning-holic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: morningholic!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
server:
  port: 9001
  servlet:
    context-path: /api

app:
  security:
    allowed-origins: "*"
    allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
    allowed-headers: "*"