spring:
  datasource:
    url: jdbc:mysql://localhost:3306/morning_holic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
server:
  port: 9000
  servlet:
    context-path: /api
aws:
  access-key: AKIA4WQKIS3FC7HXIJPV
  secret-key: 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
  s3:
    Bucket: morning-holic

app:
  security:
    allowed-origins: "*"
    allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
    allowed-headers: "*"